name: Compile Client

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: sudo sh client_src/compile.sh

            - uses: EndBug/add-and-commit@v9
              with:
                  add: "./resources/client.js --force"
                  cwd: "./"
                  message: "uploading client"
