name: Zip Resources

on:
  push:
    branches: [ master ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: resources/
          dest: resources.zip
      - uses: actions/upload-artifact@v1
        with:
          name: resources
          path: ${{ github.workspace }}/resources.zip
