name: Zip Resources

on:
  push:
    branches: [ master ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: resources/
          dest: resources2.zip