name: Zip Resources

on:
  push:
    branches: [ master ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: resources/
          dest: resources.zip
      - uses: EndBug/add-and-commit@v7
        with:
          add: "resources.zip"
          message: 'zipping resources'